### PR TITLE
Delete your own messages

### PR DESCRIPTION
**Pull request by eggistaken2**
This pull request adds the ability to delete your own messages, even if you're not a staff member or an owner of a world, there's still no easier way to delete the messages though.

### CODE REVIEW

**Comment by keef1212** [comment]
it dont work

**Comment by eggistaken2** [comment]
> it dont work

what do you mean it doesn't work?

**Comment by realredtext** [comment]
If a user were to send a sensitive message, refresh, and try to delete the message, then it would be impossible as the IDs don't match. Check for username, **not** ID (This also would prevent a user from ID-grinding to mass-delete messages).

**Comment by keef1212** [comment]
> > it dont work
> 
> what do you mean it doesn't work?

i was unable to produce the delete message thing on your owot server (shift clicking)
besides, wouldn't those messages still show up in goatway, thus making it obsolete?
falling1 could make changes to how goatway works but webhooks cannot delete their own messages so i assume this would be hard to implement

**Comment by eggistaken2** [comment]
> i was unable to produce the delete message thing on your owot server (shift clicking) besides, wouldn't those messages still show up in goatway, thus making it obsolete? falling1 could make changes to how goatway works but webhooks cannot delete their own messages so i assume this would be hard to implement

the shift clicking is not included in the main pr, it was a completely separate script

**Comment by 1052bag** [comment]
I heard people saying it will ruin the anarchy of the site, When i did the fp todo list thing

**Comment by system2k** [comment]
Not implemented to standard

**Pull request closed without merging**
