### PR TITLE
Add troll face emoji

### PR DESCRIPTION
**Pull request by dawgdawgdawg**
https://en.wikipedia.org/wiki/Trollface

:troll1: looks nothing like a troll face,
So I added :trollface: instead

### CODE REVIEW

**Comment by falling23** [comment]
, like and subscribe

**Comment by WillA-OWOT** [comment]
:troll1: exists

**Comment by dawgdawgdawg** [comment]
:troll1: doesn't even look like a troll face

**Comment by WillA-OWOT** [comment]
it doesn't need to be, it's just how kkb depicted an internet troll and it got added to the emoji roster because of its unique ascii/ansi art and it fits in with the other emojis added at the time, + the term has existed long before the trollface was even drawn
it still can be used in the same way as the trollface

**Comment by ntgowot** [comment]
this is a lot better than :troll1: for sure

**Comment by dawgdawgdawg** [comment]
> it doesn't need to be, it's just how kkb depicted an internet troll and it got added to the emoji roster because of its unique ascii/ansi art and it fits in with the other emojis added at the time, + the term has existed long before the trollface was even drawn
it still can be used in the same way as the trollface

September 19, 2008 was the date when :trollface: was drawn,
YWOT as a whole was created in 2009, with KKB going to it, and then OWOT....

**Comment by system2k** [comment]
I'll revisit this PR in the future - for now I'd like to keep the emoji set as it is

**Comment by dawgdawgdawg** [comment]
Alright

**Comment by ntgowot** [comment]
> I'll revisit this PR in the future - for now I'd like to keep the emoji set as it is

alr

**Pull request closed without merging**
